# Generated by Django 2.0.3 on 2019-08-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sicilian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regular',
            name='choice',
        ),
        migrations.DeleteModel(
            name='Regular',
        ),
    ]
