# Generated by Django 2.0.3 on 2019-08-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190831_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('regulars', models.ManyToManyField(blank=True, related_name='regulars', to='orders.Regular')),
            ],
        ),
    ]
