# Generated by Django 2.0.3 on 2019-09-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190901_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sicilians',
            field=models.ManyToManyField(blank=True, related_name='sicilians', to='orders.Sicilian'),
        ),
    ]
