# Generated by Django 2.0.3 on 2019-09-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190903_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Regular')),
                ('toppings', models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping')),
            ],
        ),
    ]
