# Generated by Django 2.0.3 on 2019-09-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_regularitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='regulars',
            field=models.ManyToManyField(blank=True, related_name='regulars', to='orders.RegularItem'),
        ),
    ]
