# Generated by Django 2.0.3 on 2019-09-12 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190906_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='SicilianItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicilian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Sicilian')),
                ('toppings', models.ManyToManyField(blank=True, related_name='sic_toppings', to='orders.Topping')),
            ],
        ),
    ]
