# Generated by Django 2.0.3 on 2019-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_cart_sicilians'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sicilians',
            field=models.ManyToManyField(blank=True, related_name='sicilians', to='orders.SicilianItem'),
        ),
    ]
