# Generated by Django 2.0.3 on 2019-09-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_pasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pastas',
            field=models.ManyToManyField(blank=True, related_name='pastas', to='orders.Pasta'),
        ),
    ]
