# Generated by Django 2.0.3 on 2019-09-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20190924_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pasta')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='pastas',
            field=models.ManyToManyField(blank=True, related_name='pastas', to='orders.PastaItem'),
        ),
    ]
