# Generated by Django 2.0.3 on 2019-09-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20190924_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaladItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Salad')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='salads',
            field=models.ManyToManyField(blank=True, related_name='salads', to='orders.SaladItem'),
        ),
    ]
